chartDraw/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace='index')),
]

index/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'index_page'

urlpatterns = [
    # /
    url(r'^$', views.index_view, name='index'),
    url(r'^manip/$', views.manip, name='manip'),
    url(r'^ictest/$', views.IC_test, name='IC_test'),
    url(r'^hypo/$', views.hypo, name='Hypo'),
    url(r'^features/$', views.features, name='features'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/templates/index/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block page_title %}{% endblock %} Chart Draw</title>

    {% load staticfiles %}
    <!-- bootstrap 4 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous"/>

    <!-- fontawesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>

    <link rel="stylesheet" type="text/css" href="{% static 'index/main.css' %}">
</head>
<body>

<nav class="navbar navbar-toggleable-md navbar-light fixed-top my-nav">

    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navMenu"
            aria-controls="navMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand" href="{% url 'index:index' %}">Chart Draw</a>

    <div class="collapse navbar-collapse" id="navMenu">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index:index' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="/features">Features</a>
        </div>
    </div>

</nav>

{% block body %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
<script src="{% static 'index/normalize.js' %}"></script>

{% block jsfiles %}
{% endblock %}

</body>
</html>

index/templates/index/features.html
{% extends 'index/base.html' %}

{% block body %}

    <style>

        .feature-card {
            margin: 150px 300px;

        }

    </style>

    <div class="container-fluid feature-card">

        <div class="row">
            <div class="card">
                <div class="card-header">
                    <h5>Présentation de l’application </h5>
                </div>
                <div class="card-block">
                    <p class="card-text">
                      ChartDraw est une petite application Web pour manipulation de données. Elle a pour but d’effectuer des calculs statistiques et d’afficher les graphes correspondants. Elle aide ainsi les data analystes à mieux interpréter les données. Son avantage est la possibilité de traiter une large dataset en ligne sans devoir installer aucun logiciel.
                    </p>
                    <p class="card-text">
                      Donc c'est mieux d'utiliser ChartDraw. Il est en version alpha pour le moment. Et n'hesiter pas a nous envoyer vos commentaire ou remarque.
                    </p>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

index/templates/index/index.html
{% extends 'index/base.html' %}

{% block body %}


    <div class="container-fluid">
        <div class="container-upload">
            <div class="col-md-4 col-sm-6 offset-md-4 offset-sm-3">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="fileName">Nommer votre fichier: </label>
                        <input type="text" class="form-control" id="fileName" name="fileName"
                               placeholder="Nom du fichier">
                    </div>
                    <br>

                    <div class="form-group">
                        <input type="file" class="form-control-file" id="fileInput" name="myfile"
                               aria-describedby="fileHelp">
                        <small id="fileHelp" class="form-text text-muted">
                            Selectioner un type de fichier puis télécharger le.
                        </small>
                    </div>

                    <br>

                    <button type="submit" class="btn btn-info btn-lg btn-block my-btn">Upload a file</button>
                </form>


            </div>
        </div>
    </div>

{% endblock %}

index/templates/index/manip.html
{% extends 'index/base.html' %}

{% block body %}
    {% load staticfiles %}

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <div class="container-fluid manip_container">

        <div class="row">
            <div class="col-4 sides sides-left">

                <h4>{{ fileName }}</h4>
                <br>

                <form method="post" action="{% url 'index_page:manip' %}">
                    {% csrf_token %}

                    <h5>Tracer des graphes: </h5>
                    <br>

                    <input type="hidden" name="file_id" value="{{ last_f }}">

                    <div class="form-group row">
                        <label for="list_graph" class="col-sm-2 col-form-label">Graphs: </label>
                        <div class="col-sm-10">
                            <select name="list_graph" class="custom-select mb-2 mr-sm-2 mb-sm-0" id="list_graph">
                                <option selected>Choisir...</option>
                                <option value="bar">Bar</option>
                                <option value="c_bar">Compare Bare</option>
                                <option value="hist">Histogram</option>
                                <option value="pie">Pie</option>
                                <option value="c_pie">Compare Pie</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="list_vars" class="col-sm-2 col-form-label">Variables</label>
                        <div class="col-sm-10">
                            <select name="list_vars" multiple class="form-control mb-2 mr-sm-2 mb-sm-0" id="list_vars">
                                {% for v in list_vars %}
                                    <option value="{{ v }}">{{ v }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button class="btn btn-success btn-sm">Tracer le graphe</button>
                        </div>
                    </div>

                </form>

                <br>
                <hr>

                <form method="post" action="{% url 'index_page:IC_test' %}">
                    {% csrf_token %}

                    <h5>Intervalle de confiance: </h5>
                    <br>

                    <input type="hidden" name="file_id" value="{{ last_f }}">

                    <div class="form-group row">
                        <label for="list_vars" class="col-sm-3 col-form-label">Variables: </label>
                        <div class="col-sm-9">
                            <select name="list_vars" class="form-control custom-select mb-2 mr-sm-2 mb-sm-0"
                                    id="list_vars">
                                {% for v in list_vars %}
                                    <option value="{{ v }}">{{ v }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="param" class="col-sm-3 col-form-label">Parametre: </label>
                        <div class="col-sm-9">
                            <select name="param" class="custom-select mb-2 mr-sm-2 mb-sm-0" id="param">
                                <option selected>Choisir...</option>
                                <option value="moy">Moyenne</option>
                                <option value="vari">Variance</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="alpha" class="col-sm-3 col-form-label">Alpha: </label>
                        <div class="col-sm-9">
                            <select name="alpha" class="custom-select mb-2 mr-sm-2 mb-sm-0" id="alpha">
                                <option selected>Choisir...</option>
                                <option value="0.01">1%</option>
                                <option value="0.05">5%</option>
                                <option value="0.1">10%</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button class="btn btn-success btn-sm">Calculer l'IC</button>
                        </div>
                    </div>

                </form>

                <br>
                <hr>

                <form method="post" action="{% url 'index_page:Hypo' %}">
                    {% csrf_token %}

                    <h5>Test d'hypothèse: </h5>
                    <br>

                    <input type="hidden" name="file_id" value="{{ last_f }}">

                    <div class="form-group row">
                        <label for="list_vars" class="col-sm-3 col-form-label">Variables: </label>
                        <div class="col-sm-9">
                            <select name="list_vars" class="form-control custom-select mb-2 mr-sm-2 mb-sm-0"
                                    id="list_vars">
                                {% for v in list_vars %}
                                    <option value="{{ v }}">{{ v }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="param" class="col-sm-3 col-form-label">Parametre: </label>
                        <div class="col-sm-9">
                            <select name="param" class="custom-select mb-3 mr-sm-3 mb-sm-0" id="param">
                                <option selected>Choisir...</option>
                                <option value="norm">Normal</option>
                                <option value="std">Student</option>
                                <option value="khi2">Khi-deux</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="alter" class="col-sm-3 col-form-label">Alternative: </label>
                        <div class="col-sm-9">
                            <select name="alter" class="custom-select mb-3 mr-sm-3 mb-sm-0" id="alter">
                                <option selected>Choisir...</option>
                                <option value="g">Gauche</option>
                                <option value="d">Droite</option>
                                <option value="b">Bilateral</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button class="btn btn-success btn-sm">Executer</button>
                        </div>
                    </div>

                </form>


            </div>

            <div class="col-8 offset-4 sides sides-right">

                <div class="plot_display">
                    <div>
                        {{ divs|safe }}
                    </div>
                    <br>
                    <div class="card card-inverse card-info">
                        <div class="card-block">
                            <p class="card-text" style="color: white;">
                                {{ divs2 }}
                            </p>
                        </div>
                    </div>
                </div>

                <br><br><br>

                <button type="button" class="btn btn-secondary affiche_desc" data-toggle="tooltip" data-placement="top"
                        title="Sommaire des fonction sur les variables">
                    <span class="span" style="display: none;">Masquer</span><span class="span">Afficher</span> le
                    tableau descriptif
                </button>
                <br>
                <br>
                <div class="affiche_desc_table dataset-display" style="display: none;">
                    {% include describe_path %}
                </div>


                <button type="button" class="btn btn-secondary affiche_table">
                    <span class="span" style="display: none;">Masquer</span><span class="span">Afficher</span> la
                    dataset
                </button>
                <br>
                <br>
                <div class="affiche_all_table dataset-display" style="display: none;">
                    {% include file_to_path %}
                </div>

            </div>
        </div>

    </div>


{% endblock %}

{% block jsfiles %}
    <script src="{% static 'index/js.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}